### ISSUE TITLE
XMWSDJ04MMC (Xiaomi Electronic Thermometer and Hygrometer) not activating?

### ISSUE THREAD

**Issue by andorardo** [pvvx/pvvx.github.io#10]
Hi Victor, I originally reported this on the ble_monitor component
https://github.com/custom-components/ble_monitor/discussions/674
but I also tried your repo directly with the same result, so I though I'd mention it here too.

Namely: I find that my XMWSDJ04MMC is timing out while I'm using https://pvvx.github.io/XMWSDJ04MMC/XMWSDJ04MMC_Utils.html to activate it.

I tried to follow the instructions with the pairing and the touching the button -- anything else that might be going on?

Here's what I reported over on ble_monitor:

---

As per the FAQ https://custom-components.github.io/ble_monitor/faq#how-to-get-the-mibeacon-v4v5-encryption-key I've had success with the LYWSD03MMC, but I'm finding that the TelinkFlasher https://atc1441.github.io/Temp_universal_mi_activate.html is hanging/timing out on the new XMWSDJ04MMC.

Anyone seen this problem?

1. I go to https://atc1441.github.io/Temp_universal_mi_activate.html
2. I click `Connect`, and pair with the XMWSDJ04MMC that appears in the list
3. The bluetooth icon on the XMWSDJ04MMC stops flashing, showing that it has paired
4. I click `Do Activation` 

and then it unfortunately hangs.

the logs show:

```
17:47:26: Searching for devices
17:47:30: Connecting to: XMWSDJ04MMC
17:47:31: Detected Mi Thermometer
17:47:31: Connected
17:47:48: Activating now, please wait...
```

and the console shows:

```
Status: Connected, you can now Do the Activation to either get the Token or flash a new Firmware
Temp_universal_mi_activate.html:386 Send: a2000000
Temp_universal_mi_activate.html:386 Enc_19: 000000000100
Temp_universal_mi_activate.html:386 Send: 00000101
Temp_universal_mi_activate.html:386 Enc_19: 010001000000
Temp_universal_mi_activate.html:386 Send: 00000100
Temp_universal_mi_activate.html:386 Send: 15000000
Temp_universal_mi_activate.html:386 Send: 000000030400
```

Anyone else had luck with the XMWSDJ04MMC?

Is there any step I'm missing?

**Comment by pvvx** [comment]
https://github.com/custom-components/ble_monitor/discussions/674#discussioncomment-2090769

**Comment by andorardo** [comment]
Hi Victor, I'm on vacation but when I get back I'll redo the instructions you posted on the forum and see if the error goes away. Maybe I have an old hardware variant. (?) If that's the case, we should make a note of it in case someone else stumbles across the same problem.

**Comment by pvvx** [comment]
Most likely the button on the thermometer was pressed incorrectly.
