### ISSUE TITLE
Random failure after updating with the ATC FW

### ISSUE THREAD

**Issue by alecsandes** [pvvx/pvvx.github.io#16]
Hi,

I have used your flasher to update 6 LYWSD03MMCs which previously ran the original FW. Prior to the update I had no issues getting the data in HA using Passive BLE HACS integration.

From the 6 hygrometers, 1 is completely not seen, 1 has issues with random and steady blackouts and one is seldomly not reporting.

Several times I get issues with connecting to those via your tool and after several connects I can connect to them.
Moving them close to the HA device or my laptop does not improve the situation, anyways, the devices are maximum 5 meters away from the RaspberryPi running HA.

A description made by on the HA forum, but I mistaken some info on the number or the hygrometers:

Hello,

I have 5 of the LYWSD03MMCs in my apartment. HA Supervised running on RPI4.

Previously running Xiaomi FW and Passive BLE integration for more than one year with few issues.

I have decided to give the custom firmware a try and flashed them with PVVX flasher, set the default advertising, 2500 with 4, BTHome discovery method, and a custom name for each.

Out of 5 units, only 3 are constantly available and sending data. 2 of them are either with unavailable data after discovery or they are not discovered at all.

I pumped the signal to +3 but without big success.

Using pvvx site I can see them, the data advertised …but on in HA,

I have also tried BLE HACS integration and only the 3 are discovered.

Trying to go back to the original FW did not yield any improvement.

Batteries were changed to new ones as well.

Does anyone have an idea where to start troubleshooting?

TIA

This is how it looks in the dashboard:

![image](https://user-images.githubusercontent.com/19631942/215856911-0e01dec7-b597-4bad-9eb8-1639755e11e1.png)

This is one with the issue:
![image](https://user-images.githubusercontent.com/19631942/215856946-639c41d1-7908-4b51-aa72-ef51532e44a1.png)

The top one (kitchen) is coming and going throughout the day (and it is the good one):

![image](https://user-images.githubusercontent.com/19631942/215856977-856069c3-f737-4a5b-a1c6-0a964a0d26e0.png)

I don't know how to address the issue as reverting to the original FW doesn't seem to restore the previous normal operation ...

**Comment by pvvx** [comment]
> Several times I get issues with connecting to those via your tool and after several connects I can connect to them.

Use version 4.2.
It partially corrects the stability of the connection for thermometers that do not have capacitors recommended by the manufacturer of chips in the power supply. These are savings from the thermometer manufacturer and cannot be corrected by software.

---

If "Passive scanning" is enabled in BTHome - enable "AdFlags":
![image](https://user-images.githubusercontent.com/12629515/226076059-b4b8ca6d-82c7-42d4-827c-5da075142ff8.png)
