### ISSUE TITLE
GraphMemo.html : limit downloaded sample

### ISSUE THREAD

**Issue by mat-c** [pvvx/pvvx.github.io#17]
Hi,
could it be possible to add an option to download only x days in GraphMemo.html  ?

Ble transfert can be long, and it could be interesting to see only last value.

Thanks

**Comment by pvvx** [comment]
Loading all 19624 samples takes 17 seconds.

When loading, the program does not know the save time step and cannot request n days. It is also unknown what was preserved and what date / time is set in the thermometer.
Only a designated number of recent samples may be requested.

Warning: Do not use ESP32 - it cannot work with BLE at normal speed and drains the batteries of all BLE devices when connected.

**Comment by pvvx** [comment]
Added ability to load only N samples
