### ISSUE TITLE
Broken Web flasher

### ISSUE THREAD

**Issue by teuchezh** [pvvx/pvvx.github.io#18]
The "Open" button on the page https://pvvx.github.io/ATC_MiThermometer/USBCOMFlashTx.html it doesn't work. Clicking has no effect.
In Dev Tools console I see this error:
![image](https://github.com/pvvx/pvvx.github.io/assets/40827089/49ad4010-f7aa-451b-980a-f662b58e7e00)
In the code I found an extra bracket that closes the array
![image](https://github.com/pvvx/pvvx.github.io/assets/40827089/77e9ae8e-26b2-417b-8f43-e63ae5b0d2b0)
After removing this extra bracket, this flasher started working locally for me.

**Comment by pvvx** [comment]
Thank you!

**Comment by teuchezh** [comment]
Fixed!
