### ISSUE TITLE
Telink-Flasher, changing bindkey, old bindkey is displayed after writing new bindkey

### ISSUE THREAD

**Issue by JsBergbau** [pvvx/pvvx.github.io#4]
After clicking "Set new Token & Bind keys" entered key reverts back to previous key. After clicking "Show all mi keys" current/correct key is shown.

![KeyChange](https://user-images.githubusercontent.com/37013344/119901487-44ee0e80-bf46-11eb-859d-3f01068d5894.gif)

**Comment by pvvx** [comment]
Most likely this is the work of cache flash. The new value is written to Flash, but the cache is not flushed.
When new keys are entered, the reboot flag is set. requires updating multiple variables in memory. This update only happens on cold initialization.

**Comment by pvvx** [comment]
Changed all memcpy() -> flash_read() for mi-keys...

**Comment by JsBergbau** [comment]
Thanks for fixing so fast. Works now.
Can you also have a look at this Pullrequest? https://github.com/pvvx/pvvx.github.io/pull/3
If you need some changes, just tell.
