### ISSUE TITLE
Telink flasher 3.1 does not activate CGG1-M nor flash it

### ISSUE THREAD

**Issue by archiespb** [pvvx/pvvx.github.io#5]
Hi! I have a new CGG1-M version with encryption. And I can't  flash custom firmware. While opened in Chrome Telink Flasher connects to but does not activate nor shows Temp/Humi values.
What kind of information I can get you to help solve this issue?

![2021-08-14_23-55-09](https://user-images.githubusercontent.com/43927989/129459778-ec514da5-f93a-4b4f-aced-f853bb9b7d0e.png)

**Comment by pvvx** [comment]
https://github.com/pvvx/ATC_MiThermometer/issues/41#issuecomment-830570681

**Comment by archiespb** [comment]
Thank you! It was very helpful.
